projects:
  tiw:
    schemaPath: amplify/backend/api/tiw/build/schema.graphql
    includes:
      - frontend/src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ""
        docsFilePath: frontend/src/graphql
extensions:
  amplify:
    version: 3
