/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ocosfj5rffbyho773fwllrsoam.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-avjyqd56rjefxnorjq7qztvniq",
    "aws_cognito_identity_pool_id": "us-east-1:58baba58-4517-4454-a33f-3288746db653",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8OFrjWuhq",
    "aws_user_pools_web_client_id": "2bp27v230dcl8rnvn8ao9v95ju",
    "oauth": {}
};


export default awsmobile;
