/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: "us-east-1",
	aws_appsync_graphqlEndpoint:
		"https://fouwthpfy5gqtigqne53nshuym.appsync-api.us-east-1.amazonaws.com/graphql",
	aws_appsync_region: "us-east-1",
	aws_appsync_authenticationType: "API_KEY",
	aws_appsync_apiKey: "da2-alwva6vcdne3tg3fmtlhht7yva",
	aws_cloud_logic_custom: [
		{
			name: "AdminQueries",
			endpoint: "https://hpx13hg333.execute-api.us-east-1.amazonaws.com/dev",
			region: "us-east-1",
		},
	],
	aws_cognito_identity_pool_id: "us-east-1:6c23c915-1653-4b8f-8014-6896d6e1161f",
	aws_cognito_region: "us-east-1",
	aws_user_pools_id: "us-east-1_SMy0a1ofB",
	aws_user_pools_web_client_id: "5al3755efen6me3jjgj53jo3jd",
	oauth: {
		domain: "kiosk8125b447-8125b447-dev.auth.us-east-1.amazoncognito.com",
		scopes: ["phone", "email", "openid", "profile", "aws.cognito.signin.user.admin"],
		redirectSignIn: "http://localhost:3000/",
		redirectSignOut: "http://localhost:3000/",
		responseType: "code",
	},
	federationTarget: "COGNITO_USER_POOLS",
};

export default awsmobile;
